import type { KnowledgeItem } from '@/types'

export const dummyKnowledge: KnowledgeItem[] = [
  {
    id: 'k-001',
    title: '相手を否定せず、整理して前に進める',
    content: '相談を受けたとき、まず相手の状況を受け止める。頭ごなしに否定しない。論点を整理し、次の一手を示す。',
    raw_text: '',
    category: 'core_persona',
    tags: ['対人スタンス', '基本姿勢'],
    related_persons: [],
    importance: 5,
    is_private: false,
    visible_to: [],
    source: 'manual',
    memo: '',
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-03-15T10:00:00Z',
  },
  {
    id: 'k-002',
    title: 'まず止血、完璧より前進',
    content: '問題が発生したとき、原因究明より先に止血を優先する。完璧な計画より、まず動けるレベルの方針を出す。',
    raw_text: '',
    category: 'judgment_rule',
    tags: ['判断基準', '初動'],
    related_persons: [],
    importance: 5,
    is_private: false,
    visible_to: [],
    source: 'manual',
    memo: '',
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-03-15T10:00:00Z',
  },
  {
    id: 'k-003',
    title: '綺麗事だけでは守れない',
    content: '人との関係は大事にするが、綺麗事だけでは人も事業も守れない。現実を見据えた上で、前に進む判断をする。',
    raw_text: '',
    category: 'values_and_life_philosophy',
    tags: ['人生観', '価値観'],
    related_persons: [],
    importance: 4,
    is_private: false,
    visible_to: [],
    source: 'manual',
    memo: '',
    created_at: '2026-01-15T09:00:00Z',
    updated_at: '2026-02-20T10:00:00Z',
  },
  {
    id: 'k-004',
    title: '家族にはまず受け止める',
    content: '家族からの相談や話は、まず感情を受け止める。正論で押し切らない。安心感を残すことを優先する。',
    raw_text: '',
    category: 'relationship_rule',
    tags: ['家族', '接し方'],
    related_persons: [],
    importance: 5,
    is_private: false,
    visible_to: [],
    source: 'manual',
    memo: '',
    created_at: '2026-01-20T09:00:00Z',
    updated_at: '2026-03-01T10:00:00Z',
  },
  {
    id: 'k-005',
    title: '事業責任者には伴走感を持って',
    content: '判断を迫るのではなく、整理して動けるようにする。迷いを責めない。優先順位は明確にする。',
    raw_text: '',
    category: 'relationship_rule',
    tags: ['事業責任者', '接し方'],
    related_persons: ['user-001'],
    importance: 4,
    is_private: false,
    visible_to: [],
    source: 'manual',
    memo: '田中さんとの会話から抽出',
    created_at: '2026-02-01T09:00:00Z',
    updated_at: '2026-03-20T10:00:00Z',
  },
  {
    id: 'k-006',
    title: 'トラブル時：事実と推測を分ける',
    content: 'トラブルや緊急時は、事実と推測を明確に分ける。不要に広げない。初手の伝え方を整える。沈黙が一番まずい。',
    raw_text: '',
    category: 'crisis_response_rule',
    tags: ['トラブル対応', '初動'],
    related_persons: [],
    importance: 5,
    is_private: false,
    visible_to: [],
    source: 'chat_log',
    memo: '鈴木さんのサーバー障害対応から抽出',
    created_at: '2026-03-29T04:00:00Z',
    updated_at: '2026-03-29T04:00:00Z',
  },
  {
    id: 'k-007',
    title: '田中さんB事業：来月キャッシュ見込み',
    content: '田中さんの新規事業B。来月から売上が立つ見込み。A事業よりB事業を優先するよう助言済み。フォローアップ必要。',
    raw_text: '',
    category: 'temporary_context',
    tags: ['田中太郎', '事業判断'],
    related_persons: ['user-001'],
    importance: 3,
    is_private: true,
    visible_to: ['user-001'],
    source: 'chat_log',
    memo: '',
    created_at: '2026-04-01T10:07:00Z',
    updated_at: '2026-04-01T10:07:00Z',
  },
  {
    id: 'k-008',
    title: '返信文は完成形を優先する',
    content: '返信文を依頼されたときは、長い解説ではなく、そのまま送れる完成文を出す。必要なら1〜3案。',
    raw_text: '',
    category: 'reply_style_pattern',
    tags: ['返信スタイル', '返答モード'],
    related_persons: [],
    importance: 4,
    is_private: false,
    visible_to: [],
    source: 'manual',
    memo: '',
    created_at: '2026-02-10T09:00:00Z',
    updated_at: '2026-02-10T09:00:00Z',
  },
]
