import type { ChangeHistory } from '@/types'

export const dummyChangeHistory: ChangeHistory[] = [
  {
    id: 'ch-001',
    entity_type: 'knowledge',
    entity_id: 'k-006',
    change_type: 'create',
    previous_value: null,
    new_value: { title: 'トラブル時：事実と推測を分ける', category: 'crisis_response_rule' },
    changed_by: 'admin-001',
    created_at: '2026-03-29T04:00:00Z',
  },
  {
    id: 'ch-002',
    entity_type: 'knowledge',
    entity_id: 'k-007',
    change_type: 'create',
    previous_value: null,
    new_value: { title: '田中さんB事業：来月キャッシュ見込み', category: 'temporary_context' },
    changed_by: 'admin-001',
    created_at: '2026-04-01T10:07:00Z',
  },
  {
    id: 'ch-003',
    entity_type: 'persona',
    entity_id: 'pr-12',
    change_type: 'update',
    previous_value: { value: '原因究明より復旧を優先。' },
    new_value: { value: '原因究明より復旧を優先。沈黙が一番まずい。' },
    changed_by: 'admin-001',
    created_at: '2026-03-29T04:00:00Z',
  },
  {
    id: 'ch-004',
    entity_type: 'relationship',
    entity_id: 'rs-001',
    change_type: 'update',
    previous_value: { strictness_level: 3 },
    new_value: { strictness_level: 2 },
    changed_by: 'admin-001',
    created_at: '2026-03-20T10:00:00Z',
  },
  {
    id: 'ch-005',
    entity_type: 'user',
    entity_id: 'user-003',
    change_type: 'create',
    previous_value: null,
    new_value: { display_name: '吉田恵子', relationship_category: 'family' },
    changed_by: 'admin-001',
    created_at: '2026-02-01T09:00:00Z',
  },
  {
    id: 'ch-006',
    entity_type: 'knowledge',
    entity_id: 'k-001',
    change_type: 'update',
    previous_value: { importance: 4 },
    new_value: { importance: 5 },
    changed_by: 'admin-001',
    created_at: '2026-03-15T10:00:00Z',
  },
]
